import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";
import "./_styles/globals.css";

export const metadata = {
  title: "Prinz Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>
          <p>&copy; 2021 Next.js</p>
        </footer>
      </body>
    </html>
  );
}
